import { useEffect, useRef, useState } from "react";
import { useRecipeStore } from "./store/useRecipeStore";
import { recipes, ingredientsData } from "./data";
import {
  formatRp,
  ingredientNames,
  recipeLabels,
  recipeIcons,
  recipePhotos,
} from "./helpers";

// ─── PDF EXPORT ───────────────────────────────────────────────────────────────
function exportPDF(
  recipe,
  portion,
  ingredients,
  totalCost,
  totalCalories,
  businessStats,
) {
  const { costPerItem, revenue, profit, margin } = businessStats;
  const label = recipeLabels[recipe] || recipe;
  const date = new Date().toLocaleDateString("en-GB");

  const rows = ingredients
    .map(
      (item) =>
        `<tr>
      <td>${ingredientNames[item.name] || item.name}</td>
      <td style="text-align:right">${item.amount.toLocaleString("id-ID")}g</td>
      <td style="text-align:right;color:#c8783a;font-weight:700">${formatRp(item.cost)}</td>
    </tr>`,
    )
    .join("");

  const html = `<!DOCTYPE html>
<html><head><meta charset="utf-8"/>
<title>${label} - Recipe Calculator</title>
<style>
  @import url('https://fonts.googleapis.com/css2?family=Playfair+Display:wght@700&family=Nunito:wght@400;600;700&display=swap');
  body{font-family:'Nunito',sans-serif;color:#3d2b1f;padding:40px;max-width:600px;margin:0 auto}
  h1{font-family:'Playfair Display',serif;color:#c8783a;font-size:28px;margin-bottom:4px}
  .sub{color:#9a7860;font-size:13px;margin-bottom:24px}
  .section{margin-bottom:24px}
  .section-title{font-family:'Playfair Display',serif;color:#8b4513;font-size:16px;border-bottom:2px solid #f0dfc8;padding-bottom:6px;margin-bottom:12px}
  table{width:100%;border-collapse:collapse}
  th{text-align:left;font-size:11px;text-transform:uppercase;letter-spacing:.5px;color:#9a7860;padding:6px 8px;border-bottom:2px solid #f0dfc8}
  td{padding:9px 8px;font-size:13px;border-bottom:1px solid #f0dfc8}
  .total-row td{font-weight:700;font-size:15px;border-top:2px dashed #f0dfc8;border-bottom:none;padding-top:12px}
  .total-row td:last-child{color:#c8783a;font-size:18px}
  .biz-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}
  .biz-card{background:#fff8f2;border:1.5px solid #f0dfc8;border-radius:10px;padding:12px}
  .biz-label{font-size:11px;text-transform:uppercase;letter-spacing:.5px;color:#9a7860;font-weight:700}
  .biz-val{font-size:18px;font-weight:700;margin-top:3px}
  .green{color:#27ae60}.red{color:#e74c3c}
  .footer{margin-top:32px;text-align:center;font-size:12px;color:#9a7860}
</style></head><body>
  <h1>🧁 ${label}</h1>
  <div class="sub">Recipe Calculator Export — ${date} — ${portion}x batch</div>
  <div class="section">
    <div class="section-title">🧂 Ingredients</div>
    <table><thead><tr><th>Ingredient</th><th style="text-align:right">Grams</th><th style="text-align:right">Price</th></tr></thead>
    <tbody>${rows}
      <tr class="total-row"><td colspan="2">Total Cost</td><td style="text-align:right">${formatRp(totalCost)}</td></tr>
      <tr><td colspan="2" style="color:#9a7860;font-size:13px">Total Calories</td><td style="text-align:right;color:#9a7860;font-size:13px">${Math.round(totalCalories).toLocaleString("id-ID")} kcal</td></tr>
    </tbody></table>
  </div>
  <div class="section">
    <div class="section-title">📊 Business Analysis</div>
    <div class="biz-grid">
      <div class="biz-card"><div class="biz-label">COGS / pcs</div><div class="biz-val">${formatRp(costPerItem)}</div></div>
      <div class="biz-card"><div class="biz-label">Total Revenue</div><div class="biz-val">${formatRp(revenue)}</div></div>
      <div class="biz-card"><div class="biz-label">Profit / Loss</div><div class="biz-val ${profit >= 0 ? "green" : "red"}">${profit >= 0 ? "+" : ""}${formatRp(profit)}</div></div>
      <div class="biz-card"><div class="biz-label">Margin</div><div class="biz-val ${margin >= 0 ? "green" : "red"}">${margin.toFixed(1)}%</div></div>
    </div>
  </div>
  <div class="footer">Generated by Recipe Calculator</div>
</body></html>`;

  const blob = new Blob([html], { type: "text/html" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${recipe}-recipe-${date.replace(/\//g, "-")}.html`;
  a.click();
  URL.revokeObjectURL(url);
}

// ─── SHARE / COPY ────────────────────────────────────────────────────────────
function buildSummaryText(
  recipe,
  portion,
  ingredients,
  totalCost,
  totalCalories,
  businessStats,
) {
  const { costPerItem, revenue, profit, margin } = businessStats;
  const label = recipeLabels[recipe] || recipe;
  const date = new Date().toLocaleDateString("id-ID");

  const ingLines = ingredients
    .map(
      (item) =>
        `  • ${ingredientNames[item.name] || item.name}: ${item.amount.toLocaleString("id-ID")}g — ${formatRp(item.cost)}`,
    )
    .join("\n");

  return [
    `🧁 *Recipe Calculator — ${label}*`,
    `📅 ${date} | 🔢 ${portion}x batch`,
    ``,
    `🧂 *Ingredients:*`,
    ingLines,
    ``,
    `💰 *Total Cost:* ${formatRp(totalCost)}`,
    `🔥 *Total Calories:* ${Math.round(totalCalories).toLocaleString("id-ID")} kcal`,
    ``,
    `📊 *Business Analysis:*`,
    `  • COGS/pcs: ${formatRp(costPerItem)}`,
    `  • Revenue:  ${formatRp(revenue)}`,
    `  • Profit:   ${profit >= 0 ? "+" : ""}${formatRp(profit)}`,
    `  • Margin:   ${margin.toFixed(1)}%`,
    ``,
    `_Generated by Recipe Calculator_ 🍪`,
  ].join("\n");
}

function ShareButton({
  recipe,
  portion,
  ingredients,
  totalCost,
  totalCalories,
  businessStats,
}) {
  const [copied, setCopied] = useState(false);
  const [showMenu, setShowMenu] = useState(false);

  const text = buildSummaryText(
    recipe,
    portion,
    ingredients,
    totalCost,
    totalCalories,
    businessStats,
  );

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setShowMenu(false);
      setTimeout(() => setCopied(false), 2500);
    } catch {
      // fallback for older browsers
      const ta = document.createElement("textarea");
      ta.value = text;
      document.body.appendChild(ta);
      ta.select();
      document.execCommand("copy");
      document.body.removeChild(ta);
      setCopied(true);
      setShowMenu(false);
      setTimeout(() => setCopied(false), 2500);
    }
  };

  const handleWhatsApp = () => {
    const encoded = encodeURIComponent(text);
    window.open(`https://wa.me/?text=${encoded}`, "_blank");
    setShowMenu(false);
  };

  return (
    <div className="share-wrap">
      <button
        className={`share-btn${copied ? " copied" : ""}`}
        onClick={() => setShowMenu((v) => !v)}
      >
        {copied ? "✅ Copied!" : "📤 Share"}
      </button>

      {showMenu && (
        <div className="share-menu">
          <button className="share-option" onClick={handleCopy}>
            📋 Copy to Clipboard
          </button>
          <button className="share-option whatsapp" onClick={handleWhatsApp}>
            💬 Send via WhatsApp
          </button>
        </div>
      )}
    </div>
  );
}

// ─── PRICE EDITOR MODAL ───────────────────────────────────────────────────────
function PriceEditor({ onClose }) {
  const customPrices = useRecipeStore((s) => s.customPrices);
  const updatePrice = useRecipeStore((s) => s.updatePrice);
  const resetPrices = useRecipeStore((s) => s.resetPrices);

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal" onClick={(e) => e.stopPropagation()}>
        <div className="modal-header">
          <span className="modal-title">💰 Edit Ingredient Prices</span>
          <button className="modal-close" onClick={onClose}>
            ✕
          </button>
        </div>
        <p className="modal-subtitle">
          Price per gram (Rp). Leave blank to use default.
        </p>
        <div className="price-grid">
          {Object.entries(ingredientsData).map(([key, data]) => (
            <div key={key} className="price-row">
              <label>{ingredientNames[key] || key}</label>
              <div className="price-input-wrap">
                <span className="price-default">
                  Default: {data.pricePerGram}/g
                </span>
                <input
                  type="number"
                  min="0"
                  placeholder={data.pricePerGram}
                  value={customPrices[key] ?? ""}
                  onChange={(e) => {
                    const val = e.target.value;
                    if (val === "") {
                      const next = { ...customPrices };
                      delete next[key];
                      useRecipeStore.setState({ customPrices: next });
                      localStorage.setItem(
                        "customPrices",
                        JSON.stringify(next),
                      );
                    } else {
                      updatePrice(key, val);
                    }
                  }}
                />
              </div>
            </div>
          ))}
        </div>
        <div className="modal-footer">
          <button className="ctrl-btn" onClick={resetPrices}>
            🔄 Reset All
          </button>
          <button className="ctrl-btn primary" onClick={onClose}>
            ✓ Done
          </button>
        </div>
      </div>
    </div>
  );
}

// ─── MAIN APP ─────────────────────────────────────────────────────────────────
export default function App() {
  const recipe = useRecipeStore((s) => s.recipe);
  const portion = useRecipeStore((s) => s.portion);
  const activeStep = useRecipeStore((s) => s.activeStep);
  const completedSteps = useRecipeStore((s) => s.completedSteps);
  const sellingPrice = useRecipeStore((s) => s.sellingPrice);
  const yieldAmount = useRecipeStore((s) => s.yieldAmount);
  const darkMode = useRecipeStore((s) => s.darkMode);
  const showPriceEditor = useRecipeStore((s) => s.showPriceEditor);

  const setRecipe = useRecipeStore((s) => s.setRecipe);
  const setPortion = useRecipeStore((s) => s.setPortion);
  const setActiveStep = useRecipeStore((s) => s.setActiveStep);
  const toggleStep = useRecipeStore((s) => s.toggleStep);
  const resetSteps = useRecipeStore((s) => s.resetSteps);
  const setSellingPrice = useRecipeStore((s) => s.setSellingPrice);
  const setYieldAmount = useRecipeStore((s) => s.setYieldAmount);
  const toggleDarkMode = useRecipeStore((s) => s.toggleDarkMode);
  const togglePriceEditor = useRecipeStore((s) => s.togglePriceEditor);
  const getCalculated = useRecipeStore((s) => s.getCalculated);
  const getBusinessStats = useRecipeStore((s) => s.getBusinessStats);

  const { ingredients, totalCost, totalCalories } = getCalculated();
  const businessStats = getBusinessStats();
  const { costPerItem, revenue, profit, margin } = businessStats;

  const safeSteps = Array.isArray(recipes[recipe]?.steps)
    ? recipes[recipe].steps
    : [];
  const progress = safeSteps.length
    ? Math.round((completedSteps.length / safeSteps.length) * 100)
    : 0;

  const stepRefs = useRef([]);

  useEffect(() => {
    document.body.className = darkMode ? "dark-mode" : "";
  }, [darkMode]);

  useEffect(() => {
    stepRefs.current[activeStep]?.scrollIntoView({
      behavior: "smooth",
      block: "nearest",
    });
  }, [activeStep]);

  return (
    <div className="app">
      <button className="theme-btn" onClick={toggleDarkMode}>
        {darkMode ? "☀️ Light" : "🌙 Dark"}
      </button>

      {showPriceEditor && <PriceEditor onClose={togglePriceEditor} />}

      {/* ── HEADER ── */}
      <div className="header">
        <img src={recipeIcons[recipe]} alt="icon" className="header-icon" />
        <img src={recipePhotos[recipe]} alt={recipe} className="header-photo" />
        <div className="header-text">
          <h1>Recipe Calculator</h1>
          <p>Smart baking calculator with business insights</p>
        </div>
      </div>

      {/* ── TABS ── */}
      <div className="recipe-tabs">
        {Object.keys(recipes).map((key) => (
          <button
            key={key}
            className={`tab-btn${recipe === key ? " active" : ""}`}
            onClick={() => setRecipe(key)}
          >
            <img src={recipeIcons[key]} alt={key} className="tab-icon" />
            {recipeLabels[key]}
          </button>
        ))}
      </div>

      {/* ── TWO COLUMN LAYOUT ── */}
      <div className="two-col">
        {/* LEFT COLUMN */}
        <div className="col-left">
          {/* SETTINGS */}
          <div className="card">
            <div className="card-title">⚙️ Settings</div>
            <div className="field">
              <label>Number of Batches</label>
              <input
                type="number"
                min="1"
                value={portion}
                onChange={(e) => setPortion(Number(e.target.value))}
              />
            </div>
          </div>

          {/* INGREDIENTS */}
          <div className="card">
            <div className="card-title">
              🧂 Ingredients
              <span className="badge">{portion}x batch</span>
              <button className="edit-price-btn" onClick={togglePriceEditor}>
                ✏️ Edit Prices
              </button>
            </div>
            <table className="ing-table">
              <thead>
                <tr>
                  <th>Ingredient</th>
                  <th className="amt-col">Grams</th>
                  <th className="cost-col">Price</th>
                </tr>
              </thead>
              <tbody>
                {ingredients.map((item, i) => (
                  <tr key={i}>
                    <td>{ingredientNames[item.name] || item.name}</td>
                    <td className="amt-col">
                      {item.amount.toLocaleString("id-ID")}g
                    </td>
                    <td className="cost-col">{formatRp(item.cost)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
            <div className="summary-row">
              <span>Total Cost</span>
              <span className="big">{formatRp(totalCost)}</span>
            </div>
            <div
              className="summary-row"
              style={{ borderTop: "none", paddingTop: 0, fontSize: 13 }}
            >
              <span style={{ color: "var(--text-muted)" }}>Total Calories</span>
              <span style={{ color: "var(--text-muted)", fontWeight: 700 }}>
                {Math.round(totalCalories).toLocaleString("id-ID")} kcal
              </span>
            </div>
            <div className="action-btns">
              <button
                className="export-btn"
                onClick={() =>
                  exportPDF(
                    recipe,
                    portion,
                    ingredients,
                    totalCost,
                    totalCalories,
                    businessStats,
                  )
                }
              >
                📄 Export PDF
              </button>
              <ShareButton
                recipe={recipe}
                portion={portion}
                ingredients={ingredients}
                totalCost={totalCost}
                totalCalories={totalCalories}
                businessStats={businessStats}
              />
            </div>
          </div>
        </div>
        {/* end col-left */}

        {/* RIGHT COLUMN */}
        <div className="col-right">
          {/* BUSINESS */}
          <div className="card">
            <div className="card-title">📊 Business Analysis</div>
            <div
              style={{
                display: "grid",
                gridTemplateColumns: "1fr 1fr",
                gap: 10,
              }}
            >
              <div className="field">
                <label>Selling Price / pcs (Rp)</label>
                <input
                  type="number"
                  min="0"
                  value={sellingPrice}
                  onChange={(e) => setSellingPrice(e.target.value)}
                />
              </div>
              <div className="field">
                <label>Yield / batch (pcs)</label>
                <input
                  type="number"
                  min="1"
                  value={yieldAmount}
                  onChange={(e) => setYieldAmount(e.target.value)}
                />
              </div>
            </div>
            <div className="biz-grid">
              <div className="biz-stat">
                <div className="label">COGS / pcs</div>
                <div className="value">{formatRp(costPerItem)}</div>
              </div>
              <div className="biz-stat">
                <div className="label">Total Revenue</div>
                <div className="value">{formatRp(revenue)}</div>
              </div>
              <div className="biz-stat">
                <div className="label">Profit / Loss</div>
                <div className={`value ${profit >= 0 ? "green" : "red"}`}>
                  {profit >= 0 ? "+" : ""}
                  {formatRp(profit)}
                </div>
              </div>
              <div className="biz-stat">
                <div className="label">Margin</div>
                <div className={`value ${margin >= 0 ? "green" : "red"}`}>
                  {margin.toFixed(1)}%
                </div>
              </div>
            </div>
          </div>

          {/* STEPS */}
          <div className="card">
            <div className="card-title">👩‍🍳 Steps</div>

            {safeSteps.length === 0 ? (
              <div className="wip-notice">
                <span className="wip-icon">🚧</span>
                <strong>
                  Steps for {recipeLabels[recipe]} are under development.
                </strong>
                <p style={{ marginTop: 6, fontSize: 13 }}>Check back soon!</p>
              </div>
            ) : (
              <>
                <div className="progress-wrap">
                  <div className="progress-label">
                    <span>Progress</span>
                    <span>
                      {completedSteps.length}/{safeSteps.length} — {progress}%
                    </span>
                  </div>
                  <div className="progress-bar">
                    <div
                      className="progress-fill"
                      style={{ width: `${progress}%` }}
                    />
                  </div>
                </div>

                {progress === 100 && (
                  <div className="done-banner">
                    🎉 All steps complete! Your {recipeLabels[recipe]} is ready!
                  </div>
                )}

                <ol className="steps-list">
                  {safeSteps.map((step, i) => {
                    const isDone = completedSteps.includes(i);
                    const isActive = i === activeStep;
                    return (
                      <li
                        key={i}
                        ref={(el) => (stepRefs.current[i] = el)}
                        className={`step-item${isActive ? " active" : ""}${isDone ? " done" : ""}`}
                        onClick={() => toggleStep(i)}
                      >
                        <div className="step-num">{isDone ? "✓" : i + 1}</div>
                        <span>{step}</span>
                      </li>
                    );
                  })}
                </ol>

                <div className="step-controls">
                  <button
                    className="ctrl-btn"
                    onClick={() => setActiveStep(Math.max(activeStep - 1, 0))}
                  >
                    ← Prev
                  </button>
                  <button
                    className="ctrl-btn primary"
                    onClick={() => toggleStep(activeStep)}
                  >
                    ✓ Done
                  </button>
                  <button
                    className="ctrl-btn"
                    onClick={() =>
                      setActiveStep(
                        Math.min(activeStep + 1, safeSteps.length - 1),
                      )
                    }
                  >
                    Next →
                  </button>
                  <button className="ctrl-btn" onClick={resetSteps}>
                    🔄 Reset
                  </button>
                </div>
              </>
            )}
          </div>
        </div>
        {/* end col-right */}
      </div>
      {/* end two-col */}
    </div>
  );
}
