// ─── TRANSLATIONS ─────────────────────────────────────────────────────────────
export const translations = {
  en: {
    // Header
    appTitle: "Recipe Calculator",
    appSubtitle: "Smart baking calculator with business insights",

    // Tabs / Nav
    darkMode: "Dark",
    lightMode: "Light",

    // Settings
    settings: "Settings",
    numberOfBatches: "Number of Batches",

    // Ingredients
    ingredients: "Ingredients",
    ingredient: "Ingredient",
    grams: "Grams",
    price: "Price",
    totalCost: "Total Cost",
    totalCalories: "Total Calories",
    editPrices: "Edit Prices",
    exportPDF: "Export PDF",
    share: "Share",
    copied: "Copied!",
    copyClipboard: "Copy to Clipboard",
    sendWhatsApp: "Send via WhatsApp",

    // Price Editor
    editIngredientPrices: "Edit Ingredient Prices",
    pricePerGram: "Price per gram (Rp). Leave blank to use default.",
    defaultPrice: "Default:",
    resetAll: "Reset All",
    done: "Done",

    // Business
    businessAnalysis: "Business Analysis",
    sellingPrice: "Selling Price / pcs (Rp)",
    yieldBatch: "Yield / batch (pcs)",
    cogsPerPcs: "COGS / pcs",
    totalRevenue: "Total Revenue",
    profitLoss: "Profit / Loss",
    margin: "Margin",

    // Steps
    steps: "Steps",
    progress: "Progress",
    prev: "Prev",
    next: "Next",
    markDone: "Done",
    reset: "Reset",
    wipTitle: "Steps under development.",
    wipSub: "Check back soon!",
    allDone: "All steps complete! Your",
    isReady: "is ready!",

    // Notes
    recipeNotes: "Recipe Notes",
    notesPlaceholder: "Add your notes, tips, or modifications here...",
    notesSaved: "Saved!",
    notesHint: "Notes are saved automatically.",

    // Ingredient names
    flour: "Wheat Flour",
    butter: "Butter",
    wisman: "Wisman",
    powdered_sugar: "Powdered Sugar",
    cornstarch: "Cornstarch",
    milk_powder: "Milk Powder",
    cheese_edam: "Edam Cheese",
    cheese_cheddar: "Cheddar Cheese",
    cashew: "Cashew Nuts",
    chocolate_block: "Chocolate Block",
    cocoa_powder: "Cocoa Powder",
    cream_of_tartar: "Cream of Tartar",
    lemon_juice: "Lemon Juice",
    coconut_milk: "Coconut Milk",
    egg_yolk: "Egg Yolk",
    sago_flour: "Sago Flour",

    // Recipe labels
    nastar: "Nastar",
    kastengel: "Kastengel",
    putri: "Putri Salju",
    sagu: "Sagu Keju",
    kompies: "Kompies",



    // Timer
    timerStart: "Start",
    timerPause: "Pause",
    timerReset: "Reset",
    timerDone: "Done!",
    timerMin: "min",

    // History
    history: "History",
    historySub: "Your recent calculation results.",
    historyEmpty: "No history yet. Start calculating!",
    historyClear: "Clear All",

    // Cost Chart
    costBreakdown: "Cost Breakdown",

    // Selling Price Calculator
    targetMarginTitle: "Auto Selling Price Calculator",
    targetMarginLabel: "Target Margin",
    suggestedPrice: "Suggested Price / pcs",
    applyPrice: "Apply This Price",

    // Label Print
    printLabel: "Print Label",
    printLabelSub: "Fill in details below. 6 labels will be printed per page.",
    brandName: "Brand Name",
    weightGram: "Weight (gram)",
    phoneNum: "Phone Number",
    expDays: "Expiry (days from today)",
    customNote: "Custom Note",
    printNow: "Print Now",

    // Share text
    shareTitle: "Recipe Calculator",
    shareBatch: "batch",
    shareIngredients: "Ingredients",
    shareBusiness: "Business Analysis",
    shareGenerated: "Generated by Recipe Calculator",
  },

  id: {
    // Header
    appTitle: "Kalkulator Resep",
    appSubtitle: "Kalkulator kue pintar dengan analisis bisnis",

    // Nav
    darkMode: "Gelap",
    lightMode: "Terang",

    // Settings
    settings: "Pengaturan",
    numberOfBatches: "Jumlah Batch",

    // Ingredients
    ingredients: "Bahan-Bahan",
    ingredient: "Bahan",
    grams: "Gram",
    price: "Harga",
    totalCost: "Total Modal",
    totalCalories: "Total Kalori",
    editPrices: "Edit Harga",
    exportPDF: "Ekspor PDF",
    share: "Bagikan",
    copied: "Tersalin!",
    copyClipboard: "Salin ke Clipboard",
    sendWhatsApp: "Kirim via WhatsApp",

    // Price Editor
    editIngredientPrices: "Edit Harga Bahan",
    pricePerGram: "Harga per gram (Rp). Kosongkan untuk pakai harga default.",
    defaultPrice: "Default:",
    resetAll: "Reset Semua",
    done: "Selesai",

    // Business
    businessAnalysis: "Analisis Bisnis",
    sellingPrice: "Harga Jual / pcs (Rp)",
    yieldBatch: "Hasil / batch (pcs)",
    cogsPerPcs: "HPP / pcs",
    totalRevenue: "Total Pendapatan",
    profitLoss: "Laba / Rugi",
    margin: "Margin",

    // Steps
    steps: "Langkah-Langkah",
    progress: "Progress",
    prev: "Sebelumnya",
    next: "Selanjutnya",
    markDone: "Selesai",
    reset: "Reset",
    wipTitle: "Langkah-langkah sedang dikembangkan.",
    wipSub: "Segera hadir!",
    allDone: "Semua langkah selesai! Kue",
    isReady: "kamu sudah siap!",

    // Notes
    recipeNotes: "Catatan Resep",
    notesPlaceholder: "Tambahkan catatan, tips, atau modifikasi resep di sini...",
    notesSaved: "Tersimpan!",
    notesHint: "Catatan disimpan otomatis.",

    // Ingredient names
    flour: "Tepung Terigu",
    butter: "Mentega",
    wisman: "Wisman",
    powdered_sugar: "Gula Halus",
    cornstarch: "Maizena",
    milk_powder: "Susu Bubuk",
    cheese_edam: "Keju Edam",
    cheese_cheddar: "Keju Cheddar",
    cashew: "Kacang Mete",
    chocolate_block: "Cokelat Blok",
    cocoa_powder: "Bubuk Kakao",
    cream_of_tartar: "Cream of Tartar",
    lemon_juice: "Air Lemon",
    coconut_milk: "Santan",
    egg_yolk: "Kuning Telur",
    sago_flour: "Tepung Sagu",

    // Recipe labels
    nastar: "Nastar",
    kastengel: "Kastengel",
    putri: "Putri Salju",
    sagu: "Sagu Keju",
    kompies: "Kompies",



    // Timer
    timerStart: "Start",
    timerPause: "Pause",
    timerReset: "Reset",
    timerDone: "Done!",
    timerMin: "min",

    // History
    history: "History",
    historySub: "Your recent calculation results.",
    historyEmpty: "No history yet. Start calculating!",
    historyClear: "Clear All",

    // Cost Chart
    costBreakdown: "Cost Breakdown",

    // Selling Price Calculator
    targetMarginTitle: "Auto Selling Price Calculator",
    targetMarginLabel: "Target Margin",
    suggestedPrice: "Suggested Price / pcs",
    applyPrice: "Apply This Price",

    // Label Print
    printLabel: "Print Label",
    printLabelSub: "Fill in details below. 6 labels will be printed per page.",
    brandName: "Brand Name",
    weightGram: "Weight (gram)",
    phoneNum: "Phone Number",
    expDays: "Expiry (days from today)",
    customNote: "Custom Note",
    printNow: "Print Now",



    // Timer
    timerStart: "Start",
    timerPause: "Pause",
    timerReset: "Reset",
    timerDone: "Done!",
    timerMin: "min",

    // History
    history: "History",
    historySub: "Your recent calculation results.",
    historyEmpty: "No history yet. Start calculating!",
    historyClear: "Clear All",


    // Timer
    timerStart: "Mulai",
    timerPause: "Jeda",
    timerReset: "Ulang",
    timerDone: "Selesai!",
    timerMin: "menit",

    // History
    history: "Riwayat",
    historySub: "Hasil kalkulasi terakhirmu.",
    historyEmpty: "Belum ada riwayat. Mulai kalkulasi!",
    historyClear: "Hapus Semua",

    // Cost Chart
    costBreakdown: "Rincian Biaya",

    // Selling Price Calculator
    targetMarginTitle: "Kalkulator Harga Jual Otomatis",
    targetMarginLabel: "Target Margin",
    suggestedPrice: "Harga Jual Saran / pcs",
    applyPrice: "Pakai Harga Ini",

    // Label Print
    printLabel: "Cetak Label",
    printLabelSub: "Isi detail di bawah. 6 label akan dicetak per halaman.",
    brandName: "Nama Brand",
    weightGram: "Berat (gram)",
    phoneNum: "Nomor Telepon",
    expDays: "Kedaluwarsa (hari dari sekarang)",
    customNote: "Catatan Khusus",
    printNow: "Cetak Sekarang",

    // Share text
    shareTitle: "Kalkulator Resep",
    shareBatch: "batch",
    shareIngredients: "Bahan-Bahan",
    shareBusiness: "Analisis Bisnis",
    shareGenerated: "Dibuat dengan Kalkulator Resep",
  },
};

export function t(lang, key) {
  return translations[lang]?.[key] ?? translations["en"][key] ?? key;
}